GET http://localhost:8080/api/65016e77f7ac3d022c2e015a
###

POST http://localhost:8080/api
Content-Type: application/json



{
    "name":"enzos"
}
###
    
PATCH http://localhost:8080/api/65017193f7ac3d022c2e016d
Content-Type: application/json


{
    "name":"larken"
}
###

DELETE http://localhost:8080/api/650170eaf7ac3d022c2e0169
###

