GET https://zuri-stage2-3zgm.onrender.com/api/65023b766b2ca26dc026d532
###

POST https://zuri-stage2-3zgm.onrender.com/api
Content-Type: application/json



{
    "name":"enzos"
}
###
    
PATCH https://zuri-stage2-3zgm.onrender.com/api/65023b766b2ca26dc026d532
Content-Type: application/json


{
    "name":"diamond"
}
###

DELETE https://zuri-stage2-3zgm.onrender.com/api/650170eaf7ac3d022c2e0169
###

